In [1]:
import pandas
import pygsheets
import numpy

## import gogpt data

In [2]:
gc = pygsheets.authorize(service_account_env_var='GDRIVE_API_CREDENTIALS')
spreadsheet = gc.open_by_key('1_AB-Di3OmQGZu9AGClF2-jRWgwYIbl_jER8nf3eV0Wg') # gogpt from may 2023

gas_plants_ssa = spreadsheet.worksheet('title', 'Africa (sub-Saharan)').get_as_df()
gas_plants_mena = spreadsheet.worksheet('title', 'Middle East & North Africa').get_as_df()
#regions_df = spreadsheet.worksheet('title', 'Regions/Subregions').get_as_df()

## calculations for gogpt data

In [3]:
gas_plants_af1 = gas_plants_ssa.loc[gas_plants_ssa.Region=='Africa']
gas_plants_af2 = gas_plants_mena.loc[gas_plants_mena.Region=='Africa']
gas_plants_africa_df = pandas.concat([gas_plants_af1, gas_plants_af2])

country_list = sorted(gas_plants_africa_df.Country.unique().tolist())

gas_plants_capacity_sum = pandas.DataFrame(0, index=country_list, columns=['Announced',
                                                                           'Pre-construction',
                                                                           'Construction'])

# make any missing capacities NaN
gas_plants_africa_df['TOTAL Capacity elec. (MW)'] = gas_plants_africa_df['TOTAL Capacity elec. (MW)'].astype(str)
gas_plants_africa_df['TOTAL Capacity elec. (MW)'] = gas_plants_africa_df['TOTAL Capacity elec. (MW)'].str.replace(',','')
gas_plants_africa_df['TOTAL Capacity elec. (MW)'].replace(['','not found'],numpy.nan,inplace=True)
gas_plants_africa_df['TOTAL Capacity elec. (MW)'] = gas_plants_africa_df['TOTAL Capacity elec. (MW)'].astype(float)

status_rename = {'announced':'Announced',
                 'cancelled':'Cancelled',
                 'construction':'Construction',
                 'mothballed':'Mothballed',
                 'operating':'Operating',
                 'pre-constructoin':'Pre-construction',
                 'retired':'Retired',
                 'shelved':'Shelved'}

#gas_plants_africa_df.groupby(['Country','Status'])['TOTAL Capacity elec. (MW)'].sum().unstack().replace(numpy.nan,0)

gas_plants_capacity_sum['Announced'] += gas_plants_africa_df.loc[gas_plants_africa_df.Status=='announced'].groupby(
        'Country')['TOTAL Capacity elec. (MW)'].sum()
gas_plants_capacity_sum['Pre-construction'] += gas_plants_africa_df.loc[gas_plants_africa_df.Status=='pre-construction'].groupby(
        'Country')['TOTAL Capacity elec. (MW)'].sum()
gas_plants_capacity_sum['Construction'] += gas_plants_africa_df.loc[gas_plants_africa_df.Status=='construction'].groupby(
        'Country')['TOTAL Capacity elec. (MW)'].sum()

gas_plants_capacity_sum.replace(numpy.nan,0,inplace=True)

In [168]:
gas_plants_capacity_sum

                       Announced  Pre-construction  Construction
Algeria                      0.0               0.0        4577.0
Angola                       0.0            1770.0           0.0
Benin                        0.0             144.0           0.0
Botswana                     0.0               0.0           0.0
Cameroon                    85.0             265.0           0.0
Côte d'Ivoire                0.0               0.0         762.0
DR Congo                   200.0               0.0           0.0
Djibouti                     0.0               0.0           0.0
Egypt                        0.0             125.0         250.0
Eswatini                   250.0               0.0           0.0
Ethiopia                     0.0               0.0           0.0
Ghana                        0.0             200.0           0.0
Kenya                      700.0               0.0           0.0
Libya                        0.0            6238.0        2264.0
Mali                         0.0               0.0           0.0
Mauritania                   0.0               0.0           0.0
Morocco                   2400.0               0.0         457.0
Mozambique                 200.0            2574.0         500.0
Namibia                      0.0             493.0           0.0
Nigeria                  18482.0            1350.0        1411.0
Republic of the Congo      566.0               0.0           0.0
Réunion                      0.0               0.0           0.0
Senegal                    125.0               0.0         300.0
Sierra Leone                 0.0               0.0          89.0
Somalia                      0.0               0.0           0.0
South Africa              6465.0           10177.0           0.0
Sudan                     1470.0               0.0         575.0
Tanzania                   300.0               0.0           0.0
Togo                         0.0               0.0           0.0
Tunisia                      0.0             900.0           0.0
Zambia                       0.0               0.0           0.0
Zimbabwe                   900.0               0.0           0.0

## import goget data

looks like there's two sheets, a main data sheet and a production/reserves sheet

the main sheet has all projects, the production sheet only has those projects that have production data

* use main sheet to move through unit ids
  * for each unit id in main sheet, collect anything that's gas in the production/reserves sheet
  * do a sum of that gas m^3, store it in main sheet

In [71]:
spreadsheet = gc.open_by_key('1sJj5EvU1F9F2eTNvqyAFgEK_953kSh0RdbfOGZd78Co') # gogpt from may 2023

goget_repro_df = spreadsheet.worksheet('title', 'Reserves and Production').get_as_df()
goget_main_df = spreadsheet.worksheet('title', 'Main data').get_as_df()
goget_regions_df = spreadsheet.worksheet('title', 'Country Names and Region Definitions').get_as_df()

# remove any unused unit ids by filtering out the rows without a unit name
goget_main_df = goget_main_df.loc[goget_main_df['Unit Name']!='']
goget_repro_df = goget_repro_df.loc[goget_repro_df['Unit Name']!='']

# set unit id to the index for goget main
goget_main_df.set_index('Unit ID', inplace=True)

In [155]:
goget_regional_countries = goget_regions_df.loc[goget_regions_df['GEM region'].isin(['Africa'])]
goget_repro_region_df = goget_repro_df.loc[goget_repro_df.Country.isin(goget_regional_countries['GEM Standard Country Name'].tolist())]
goget_main_region_df = goget_main_df.loc[goget_main_df.Country.isin(goget_regional_countries['GEM Standard Country Name'].tolist())]
unit_id_list = goget_main_region_df.index.unique().tolist()

reserves_sum = pandas.DataFrame(0, index=country_list, columns=['Discovered',
                                                                'In development'])

goget_repro_region_gas_df = goget_repro_region_df.loc[goget_repro_region_df['Fuel description'].str.contains('gas')]

#add a status column to repro corresopnding to main
goget_main_region_df.loc[:,'Gas volume'] = numpy.nan
for idx,row in goget_repro_region_gas_df.iterrows():
    if row['Unit ID'] in unit_id_list:
        pass
        goget_repro_subset = goget_repro_region_gas_df.loc[goget_repro_region_gas_df['Unit ID']==row['Unit ID']]
        goget_main_region_df.loc[row['Unit ID'],'Gas volume'] = goget_repro_subset['Quantity (converted)'].sum(min_count=0)
    else:
        print('missing')

/var/folders/fl/t07mc8053p33mn6mdmvp45580000gn/T/ipykernel_26193/2591665788.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  goget_main_region_df.loc[:,'Gas volume'] = numpy.nan

In [164]:
reserves_sum['Discovered'] = goget_main_region_df.groupby(['Country','Status'])['Gas volume'].sum().unstack()[['discovered']]#[['in development']]
reserves_sum['In development'] = goget_main_region_df.groupby(['Country','Status'])['Gas volume'].sum().unstack()[['in development']]
reserves_sum.replace([numpy.nan],0,inplace=True)

In [172]:
reserves_count = pandas.DataFrame(0, index=country_list, columns=['Discovered',
                                                                'In development'])

reserves_count['Discovered'] = goget_main_region_df.groupby(['Country','Status'])['Gas volume'].count().unstack()[['discovered']]#[['in development']]
reserves_count['In development'] = goget_main_region_df.groupby(['Country','Status'])['Gas volume'].count().unstack()[['in development']]
reserves_count.replace([numpy.nan],0,inplace=True)

In [173]:
reserves_count

                       Discovered  In development
Algeria                       0.0             5.0
Angola                        1.0             1.0
Benin                         0.0             0.0
Botswana                      0.0             0.0
Cameroon                      0.0             0.0
Côte d'Ivoire                 0.0             0.0
DR Congo                      0.0             0.0
Djibouti                      0.0             0.0
Egypt                         4.0             9.0
Eswatini                      0.0             0.0
Ethiopia                      2.0             0.0
Ghana                         0.0             1.0
Kenya                         0.0             0.0
Libya                         0.0             1.0
Mali                          0.0             0.0
Mauritania                    1.0             1.0
Morocco                       1.0             0.0
Mozambique                    2.0             6.0
Namibia                       0.0             0.0
Nigeria                       0.0             7.0
Republic of the Congo         0.0             0.0
Réunion                       0.0             0.0
Senegal                       0.0             2.0
Sierra Leone                  0.0             0.0
Somalia                       0.0             0.0
South Africa                  1.0             2.0
Sudan                         0.0             0.0
Tanzania                     16.0             0.0
Togo                          0.0             0.0
Tunisia                       0.0             0.0
Zambia                        0.0             0.0
Zimbabwe                      0.0             0.0